name: WarsawTransport
options:
  bundleIdPrefix: eu.azarov
packages:
  MapboxMaps:
    url: https://github.com/mapbox/mapbox-maps-ios
    from: 11.0.0
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    branch: observation-beta
targets:
  WarsawTransport:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources: [WarsawTransport]
    settings:
      CURRENT_PROJECT_VERSION: 0
      MARKETING_VERSION: 0.0.1
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
    postBuildScripts:
      - path: scripts/insert_mapbox_token.sh
        name: Insert Mapbox Access Token
        showEnvVars: false
        basedOnDependencyAnalysis: false
        inputFiles:
          - $(TARGET_BUILD_DIR)/$(INFOPLIST_PATH)
      - path: scripts/insert_ztm_apikey.sh
        name: Insert ZTM API key
        showEnvVars: false
        basedOnDependencyAnalysis: false
        inputFiles:
          - $(TARGET_BUILD_DIR)/$(INFOPLIST_PATH)
    dependencies:
      - package: MapboxMaps
      - package: ComposableArchitecture